### ISSUE TITLE
pytanie do zadania 3

### ISSUE THREAD

**Issue by kkarkowska** [korona-science/homework-kkarkowska#1]
Cześć, 
mam dwie wątpliwości co do zadania 3 ("Returns the number of countries/regions where the infection count in a given day was NOT the same as the previous day.")
1) wydaje mi się, że z polecenia wynika, że mamy podać liczbę krajów ("Country/Region"), więc należałoby wykonać groupby po tej kolumnie, ale wtedy wynik nie są zgodnie z wynikami podanymi w opisie funkcji
2) czasem występują takie przypadki, że różnica w liczbie zachorowań jest mniejsza od 0, warto może na to zwrócić uwagę podczas kolejnego live'a:
![pytanie](https://user-images.githubusercontent.com/31347287/76900008-dd93f380-6898-11ea-9882-10bcdc2364d2.JPG)

**Comment by RouNNdeL** [comment]
Piszę to już po raz 100... Na slacku, na facebooku kilkukrotnie była zamieszczana informacja o błędzie w treści zadania 3. Co do sytuacji z ujemnymi liczbami jest to problem data setu, w momencie pisania testów takie przypadki nie występowały.

**Comment by RouNNdeL** [comment]
Dziękuję za to za dokładnie opisane wątpliwości, bardzo miło było przeczytać coś co nie brzmiało 
> Nie działa
oraz dotyczyło problemów z indentacją :)
